const INITIAL_ROWS = 10;
const MIN_ROWS = 5;
const MAX_ROWS = 20;
const COLS = 10;
const MINES = 10;
const TIME_LIMIT_SECONDS = 180;
const TIME_REWARD_CHANCE = 0.001;
const TIME_REWARD_SECONDS = 10;
const TIME_REWARD_LIFETIME_SECONDS = 10;
const NEW_ROW_INTERVAL_SECONDS = 10;
const MIN_NEW_ROW_INTERVAL_SECONDS = 3;
const DIFFICULTY_STEP_SECONDS = 30;
const ROW_CLEAR_ANIMATION_MS = 320;
const ROW_GROW_ANIMATION_MS = 360;
const DOUBLE_CLICK_MS = 300;
const LONG_PRESS_MS = 450;

const GAME_STATES = {
  READY: 'ready',
  PLAYING: 'playing',
  WON: 'won',
  LOST: 'lost'
};

module.exports = {
  INITIAL_ROWS,
  MIN_ROWS,
  MAX_ROWS,
  COLS,
  MINES,
  TIME_LIMIT_SECONDS,
  TIME_REWARD_CHANCE,
  TIME_REWARD_SECONDS,
  TIME_REWARD_LIFETIME_SECONDS,
  NEW_ROW_INTERVAL_SECONDS,
  MIN_NEW_ROW_INTERVAL_SECONDS,
  DIFFICULTY_STEP_SECONDS,
  ROW_CLEAR_ANIMATION_MS,
  ROW_GROW_ANIMATION_MS,
  DOUBLE_CLICK_MS,
  LONG_PRESS_MS,
  GAME_STATES
};
