const INITIAL_ROWS = 9;
const MAX_ROWS = 18;
const COLS = 9;
const MINES = 10;
const NEW_ROW_INTERVAL_SECONDS = 10;
const ROW_CLEAR_ANIMATION_MS = 320;
const DOUBLE_CLICK_MS = 300;
const LONG_PRESS_MS = 450;

const GAME_STATES = {
  READY: 'ready',
  PLAYING: 'playing',
  WON: 'won',
  LOST: 'lost'
};

module.exports = {
  INITIAL_ROWS,
  MAX_ROWS,
  COLS,
  MINES,
  NEW_ROW_INTERVAL_SECONDS,
  ROW_CLEAR_ANIMATION_MS,
  DOUBLE_CLICK_MS,
  LONG_PRESS_MS,
  GAME_STATES
};
